services:
  app:
    container_name: les_bookstore_backend_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    env_file:
      - .env
    depends_on:
      - postgres
    command: yarn run start:dev

  postgres:
    container_name: les_bookstore_postgres_container
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Test database for E2E tests
  postgres-test:
    container_name: les_bookstore_postgres_test_container
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookstore_test_db
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    tmpfs:
      - /var/lib/postgresql/data # Use tmpfs for faster test performance

volumes:
  postgres_data:
  postgres_test_data: